### ISSUE TITLE
Hide power menu for non-admin users

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#1074]
Non-admin users don't have permission to restart or shutdown the system, so they get 403 Forbidden when selecting these options. So it would be better to just hide the power menu.

**Comment by SunilMohanAdapa** [comment]
The number of times I use the restart function of my FreedomBox is handful of times are year mostly when device is misbehaving. We intend FreedomBox's day-to-day functioning to be always on for most of our users. Hence, we should not give this very rarely used function one of the most visible and easily accessible places in our UI.

**Comment by JosephKiranBabu** [comment]
Agreed. Let's remove the power button from the header since it doesn't deserve that prominent position.

**Comment by mray** [comment]
Disagree strongly. The power button is the KEY difference to using cloud services. *You are in control.* And even if you don't need it often, you need to find it easily.

Consider this:  
I don't turn power off my TV that often, but if I had to search for the power button in the menu, when I need it to be off, I'd not be happy. Also imagine that *this TV would even have that button* while most other TVs are remotely turned off by the manufacturer.

Just hide it for not-logged in users.

**Comment by SunilMohanAdapa** [comment]
A lot of things in FreedomBox put us in control compared to cloud services, we can't make the same argument for all of them add those in the top menu.

Most people do turn off their TVs and turning TVs off is a *very* commonly used function (next to turning it on).

We don't have 'turn off' and 'reboot' functions in most Wi-Fi router / NAS interfaces for this same reason.

**Comment by mray** [comment]
> A lot of things in FreedomBox put us in control compared to cloud services, we can't make the same argument for all of them add those in the top menu.

FreedomBox is an exception because it is a tangible devices that you operate. 
A key feature to owning a devices is the control whether it operates or not. 

> Most people do turn off their TVs and turning TVs off is a very commonly used function (next to turning it on).
(My analogy was not aiming at "standby" but the cutting of electrical power)

> We don't have 'turn off' and 'reboot' functions in most Wi-Fi router / NAS interfaces for this same reason.

Those are single purpose devices, like part of an infrastructure and routers most often don't belong to you. Btw my NAS has the entry very close to where we have it:

![image](https://user-images.githubusercontent.com/164785/31706690-13eb54de-b3ea-11e7-9c21-43ed6ce75b85.png)

I would not be opposed to stick those options in the user dropdown menu either.

**Comment by JosephKiranBabu** [comment]
FreedomBox as I see it is a collection of servers (software) and is thus a server machine (hardware). Servers are usually supposed to be never turned off. Hence I believe it's a rare use case which doesn't deserve a prominent place in the header. 

Putting restart and shutdown in the user dropdown is definitely an improvement, but I still don't see the need to have shortcuts for restart and shutdown since they're so rarely used.

**Comment by SunilMohanAdapa** [comment]
Let us then settle down on moving the restart and shutdown items to user drop down as follows:
```
Edit
Change Password
---
Restart
Shut down
---
Logout
```
The three lines after change password will only appear for admin users.

This is ordered so that 'Logout' something users expect to find at the end of the menu is found there.

**Comment by mray** [comment]
I agree that power/reboot isn't a frequently used feature, and therefore does not need to be especially  prominent. I think it is important *mostly* for psychological reasons. I can't back up my opinion with facts or data, all I can do is present my rationale:

#### My rationale
Our project is unique as it puts people in the position to be in control of something that usually is only operated by experts. Almost like giving average people access to the cockpit of a Boeing707 - which may seem crazy! But we are bold and face the challenge. In that process we mostly remove options, configurations and unnecessary steps that are in the way. And the power switch should be an exception here, not because it is used so often, but because it is literally the *ultimate* control over the hardware and more importantly: users know perfectly what this one button does and how to use it. So leaving the power button in their hands isn't a result of optimizing efficiency, but creating familiarity, trust and giving the feeling of being in charge. You don't own what you can't shut down, lets be clear about that in our interface.

That is all I have to say about the matter.

**Comment by mray** [comment]
> Let us then settle down on moving the restart and shutdown items to user drop down

That's fine with me!
