### ISSUE TITLE
transmission: Still using http authentication after upgrade

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#1139]
After upgrade to Plinth 0.17.0, Transmission still requests a username and password, even when logged in to Plinth. I think we probably should upgrade users' configurations to use SSO. Although this may be disruptive, since it will disable their current login to Transmission.

**Comment by JosephKiranBabu** [comment]
@jvalleroy Looks like the version number of transmission was not incremented. Hence transmission setup wasn't triggered which will disable transmission's auth and reload the apache configuration. 
Can you please increment the version number, restart plinth and check if SSO works?

**Comment by JosephKiranBabu** [comment]
@jvalleroy I did a thorough testing of this issue. 
The fix is indeed changing the version number, but I observed something else. The changes didn't get applied till I restarted the apache2 server. 
If the version number is incremented and plinth is restarted, transmission ends up with no auth whatsoever. It's only after restarting the apache server that the SSO got applied. This server restart should also be automated when plinth upgrades happen.
