### ISSUE TITLE
Network manager: fix CSRF when activating/deactivating network connections

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/Plinth#127]
Although the need for UUID makes things difficult to do an actual attack, we should still have a CSRF token and POST request for activating and deactivation network connections.

**Comment by stalexan** [comment]
It looks like this issue can be closed. I see a `csrftoken` cookie for both activate and deactive.

For example, for an activate I see:
<pre>
+4453:55dbc0d0:7|GET /plinth/sys/networks/e12c995b-8e79-49eb-bfda-66c3dc8084f3/activate/ 
HTTP/1.1|Host:192.168.122.231|User-Agent:Mozilla/5.0 (X11; Linux x86_64; rv%3a38.0) 
Gecko/20100101 Firefox/38.0 Iceweasel/38.2.0|Accept:text/html,application/xhtml+xml,application
/xml;q=0.9,*/*;q=0.8|Accept-Language:en-US,en;q=0.5|Accept-Encoding:gzip, 
deflate|Referer:https%3a//192.168.122.231/plinth/sys/networks
/|Cookie:csrftoken=1OQt0NGpaRWexv8vYaJa1zU3agu7PNbn; 
sessionid=flh9xsqvoinlimh9a8bpkkqhfi0gngm2; openid_selection=othersignin|Connection:keep-alive
</pre>

And for a deactivate I see:
<pre>
+4453:55dbbf37:2|GET /plinth/sys/networks/e12c995b-8e79-49eb-bfda-66c3dc8084f3/deactivate/ 
HTTP/1.1|Host:192.168.122.231|User-Agent:Mozilla/5.0 (X11; Linux x86_64; rv%3a38.0) 
Gecko/20100101 Firefox/38.0 Iceweasel/38.2.0|Accept:text/html,application/xhtml+xml,application
/xml;q=0.9,*/*;q=0.8|Accept-Language:en-US,en;q=0.5|Accept-Encoding:gzip, 
deflate|Referer:https%3a//192.168.122.231/plinth/sys/networks
/|Cookie:csrftoken=1OQt0NGpaRWexv8vYaJa1zU3agu7PNbn; 
sessionid=flh9xsqvoinlimh9a8bpkkqhfi0gngm2; openid_selection=othersignin|Connection:keep-alive
</pre>

It would be interesting to test this, and make sure Plinth is processing the token. How would I change the token on an outgoing request in the browser to see if Plinth returns an error?

The [Django docs on CSRF](https://docs.djangoproject.com/en/1.8/ref/csrf/#using-csrf), though, seem to say that CSRF checks are enabled by default for Plinth because it has `django.middleware.csrf.CsrfViewMiddleware` in `MIDDLEWARE_CLASSES`.

**Comment by SunilMohanAdapa** [comment]
On 08/25/2015 07:32 AM, Sean Alexandre wrote:
> It looks like this issue can be closed. I see a |csrftoken| cookie for
> both activate and deactive.
> 
> For example, for an activate I see:
> 
> +4453:55dbc0d0:7|GET /plinth/sys/networks/e12c995b-8e79-49eb-bfda-66c3dc8084f3/activate/ 
> HTTP/1.1|Host:192.168.122.231|User-Agent:Mozilla/5.0 (X11; Linux x86_64; rv%3a38.0) 
> Gecko/20100101 Firefox/38.0 Iceweasel/38.2.0|Accept:text/html,application/xhtml+xml,application
> /xml;q=0.9,*/*;q=0.8|Accept-Language:en-US,en;q=0.5|Accept-Encoding:gzip, 
> deflate|Referer:https%3a//192.168.122.231/plinth/sys/networks
> /|Cookie:csrftoken=1OQt0NGpaRWexv8vYaJa1zU3agu7PNbn; 
> sessionid=flh9xsqvoinlimh9a8bpkkqhfi0gngm2; openid_selection=othersignin|Connection:keep-alive
> 
> And for a deactivate I see:
> 
> +4453:55dbbf37:2|GET /plinth/sys/networks/e12c995b-8e79-49eb-bfda-66c3dc8084f3/deactivate/ 
> HTTP/1.1|Host:192.168.122.231|User-Agent:Mozilla/5.0 (X11; Linux x86_64; rv%3a38.0) 
> Gecko/20100101 Firefox/38.0 Iceweasel/38.2.0|Accept:text/html,application/xhtml+xml,application
> /xml;q=0.9,*/*;q=0.8|Accept-Language:en-US,en;q=0.5|Accept-Encoding:gzip, 
> deflate|Referer:https%3a//192.168.122.231/plinth/sys/networks
> /|Cookie:csrftoken=1OQt0NGpaRWexv8vYaJa1zU3agu7PNbn; 
> sessionid=flh9xsqvoinlimh9a8bpkkqhfi0gngm2; openid_selection=othersignin|Connection:keep-alive
> 
> It would be interesting to test this, and make sure Plinth is processing
> the token. How would I change the token on an outgoing request in the
> browser to see if Plinth returns an error?
> 

IIUC, Django does CSRF checks only on POST requests.  I believe that
what we have is not enough.

Here is how we can test this:

- Create a simple HTML page simulating an attacker.  In the page, add
<img
src="https://192.168.122.231/plinth/sys/networks/e12c995b-8e79-49eb-bfda-66c3dc8084f3/deactivate/">
.  Although difficult, assume that attacker knows the GUID if your
network connection.

- Login to Plinth.

- Visit the attack page while watching network connections in Firefox
console.

- We will find that the network connection successfully is deactivated.
 We will also find that the network response is a proper response that
we get when we deactivate the network connection (perhaps redirection to
the networks:index page).  The attack page will itself not show much.

-- 
Sunil

**Comment by bharathCh** [comment]
In Django, in django.middleware.csrf.CsrfViewMiddleware - process_view method, CSRF token validation is not checked for 'GET', 'HEAD', 'OPTIONS', 'TRACE' methods. That is why i think there is no effect of csrf_token. We can override the middleware or we can convert the call to POST.

Please advice.

**Comment by stalexan** [comment]
Hi  @bharathCh, I'm working on this one now, and will fix it. I'm changing the drop-down button to use POST instead of GET.
I was able to reproduce the problem @SunilMohanAdapa described, with the activate/deactivate possible using an <img>.

**Comment by bharathCh** [comment]
Hi @stalexan , sure, please go ahead and fix it.

**Comment by SunilMohanAdapa** [comment]
#212 got merged and that fixes this issue.
