### ISSUE TITLE
Networks: No way to activate/deactivate connections with JavaScript disabled.

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#173]
The Active / Not Active drop-down does not work with JS disabled. Maybe a simple workaround would be that clicking the button itself causes the Active / Not Active state to toggle. (And possibly the workaround can be disabled when JS is enabled.)

**Comment by SunilMohanAdapa** [comment]
On 08/06/2015 05:46 PM, James Valleroy wrote:
> The Active / Not Active drop-down does not work with JS disabled. Maybe
> a simple workaround would be that clicking the button itself causes the
> Active / Not Active state to toggle. (And possibly the workaround can be
> disabled when JS is enabled.)

Another option is to generate text like "Active" with button next to it
"De-activate" and "Inactive" with button next to it "Activate" only for
non-javascript version.  We can keep the current appearance for
javascript version.  This can done with <noscript> tag I suppose.

-- 
Sunil

**Comment by stalexan** [comment]
A related issue is that Bootstrap is currently broken in sid:
[#786429: libjs-bootstrap requires newer (non-packaged) version of jquery](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=786429)

The workaround is to use the upstream libraries, with this change in `templates/base.html`:
<pre>
diff --git a/plinth/templates/base.html b/plinth/templates/base.html
index 5d7a107..91b53c3 100644
--- a/plinth/templates/base.html
+++ b/plinth/templates/base.html
@@ -180,10 +180,9 @@
   &lt;!-- JavaScript &lt;script&gt; tags are placed at the end of the document to speed up initial page loads--&gt;
   &lt;!-- Local link to system Modernizr (includes HTML5 Shiv) --&gt;
   &lt;script type="text/javascript" src="{% static '/javascript/modernizr/modernizr.min.js' %}"&gt;&lt;/script&gt;
-  &lt;!-- Local link to system jQuery --&gt;
-  &lt;script type="text/javascript" src="{% static '/javascript/jquery/jquery.min.js' %}"&gt;&lt;/script&gt;
-  &lt;!-- Local link to system Bootstrap JS --&gt;
-  &lt;script type="text/javascript" src="{% static '/javascript/bootstrap/js/bootstrap.min.js' %}"&gt;&lt;/script&gt;
+
+  &lt;script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"&gt;&lt;/script&gt;
+  &lt;script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"&gt;&lt;/script&gt;
 
   {% block app_js %}&lt;!-- placeholder for app-specific js files --&gt;{% endblock %}
   {% block page_js %}&lt;!-- placeholder for page-specific js files --&gt;{% endblock %}
</pre>

**Comment by SunilMohanAdapa** [comment]
When we include scripts from external servers, we run into the following problems:

- External parties can track all the users of FreedomBox devices breaking user's privacy.

- External parties (or their compromised servers) can serve malicious code compromising user's security.

In the end, we are ultimately trying to build alternatives to centralized mechanisms like that.  The bug report above was filed by FreedomBox developer working on Plinth.  The reason he didn't fix it immediately is because the solution is not straight forward considering the above.

Although the bug is really important to fix, I am not sure what the solution can be.  But since we are using bootstrap's javascript in very few places, perhaps we can write our own Javascript to replace it (based on the original code of course).  We can get rid of the hack after the bug is fixed.

**Comment by SunilMohanAdapa** [comment]
Newer version of Jquery as required by Boostrap is now available in Debian.  Upgrading libjs-jquery fixed the problem for me.

**Comment by stalexan** [comment]
I agree. I only meant this as a workaround, and not a fix.

**Comment by SunilMohanAdapa** [comment]
On 08/26/2015 05:47 AM, Sean Alexandre wrote:
> I agree. I only meant this as a workaround, and not a fix.

Apologies, I misunderstood.
