### ISSUE TITLE
File descriptor leak when querying if a package is installed

### ISSUE THREAD

**Issue by stacycockrum** [freedombox/Plinth#381]
I apologize.  I accidentally closed the original item.  Attached is the status log related to item #378.
[20160116statuslog.txt](https://github.com/freedombox/Plinth/files/93625/20160116statuslog.txt)

**Comment by SunilMohanAdapa** [comment]
Looking at the log, I believe this is what happened:
- The OpenVPN setup ran for more than 4 hours on Raspberry Pi 2!  (I am starting to wonder if I made a right call to generate 4096 bit key instead of 2048 bit key).
- During this time, the show status page ran several hundreds of times.
- Each time it ran it was leaking one or more open file descriptors.
- This eventually exhausted the number of open files Plinth can hold (1024) and caused the error.

@stacycockrum , if my above theory is correct, you can try a work around: start the OpenVPN setup process, close your Plinth UI web page.  Come back next day and see that the setup completed successfully.  You can check the process once in a while, but don't keep the browser window (which continuously refreshes the status) open.

**Comment by stacycockrum** [comment]
Thank you.  I'll give that a try and report back.

**Comment by stacycockrum** [comment]
I uninstalled openvpn last night.  Reinstalled it and reinitiated the setup about 2 hours ago and closed the browser window, as instructed.  Just checked the progress and the setup completed and openvpn is running.  It looks like it's fixed on my side.  Should I close this issue?

**Comment by SunilMohanAdapa** [comment]
On 01/20/2016 04:26 AM, stacycockrum wrote:
> I uninstalled openvpn last night. Reinstalled it and reinitiated the
> setup about 2 hours ago and closed the browser window, as instructed.
> Just checked the progress and the setup completed and openvpn is
> running. It looks like it's fixed on my side. Should I close this issue?

Please keep this issue open, there is an underlying issue with Plinth
leaking file descriptors that we should fix.

After a bit of investigation, I noticed that any page that queries
whether a package is installed is leaking file descriptors in
packages.check_is_installed() method when doing resolve.

-- 
Sunil

**Comment by jvalleroy** [comment]
Fixed in #493.
