### ISSUE TITLE
No networks page after update to 0.8.2-1

### ISSUE THREAD

**Issue by bhuvankrishna** [freedombox/Plinth#436]
I am using plinth from debian repo and not from development. After updating & upgrading the system when I tried to access network tab its asking to install the application. I check /var/log/plinth/status.log and there is noting suspicious. Please check the screenshot.
![selection_056](https://cloud.githubusercontent.com/assets/592449/14117490/8bc2a176-f602-11e5-9d27-b9c79e0c7359.png)

**Comment by SunilMohanAdapa** [comment]
This is a one time dialog that will happen with due to new setup mechanism being implemented. Clicking on install will do nothing and work as usual.  We didn't want to write elaborate code just to avoid this.  Also new images will not see this.  I am closing this as we don't want to deal with this.  Please feel free to reopen for more discussion.
