### ISSUE TITLE
Certificates (Let's Encrypt) fail

### ISSUE THREAD

**Issue by mray** [freedombox/Plinth#495]
Upon pressing the "Obtain" button on Let's Encrypt I get the following error:
> Failed to obtain certificate for domain freedombox.domain.de: 2016-06-10 07:14:04,477:WARNING:certbot.client:Registering without email! Failed authorization procedure. freedombox.domain.de (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Could not connect to http://freedombox.domain.de/.well-known/acme-challenge/OCpwDfSyEozJRFJtTbnDSjG_XpacqV0SJMisOsSdusr

The second click interestingly results in a slightly different error not mentioning email:
> Failed to obtain certificate for domain freedombox.domain.de: Failed authorization procedure. freedombox.domain.de (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Could not connect to http://freedombox.domain.de/.well-known/acme-challenge/OCpwDfSyEozJRFJtTbnDSjG_XpacqV0SJMisOsSdusr

Am I supposed to provide the port through which my box is made accessible?
If so that would need some indication somewhere.

**Comment by SunilMohanAdapa** [comment]
The first message contains an extra warning because it is the first time letsencrypt invoked.  This is the time anonymous registration happens.  Later, the message disappears because registration is already done.

It looks like freedombox.domain.de is not reachable from outside and that is the problem.  Please ensure that Dynamic DNS or whatever other mechanism is being used for freedombox.domain.de is properly working.

**Comment by mray** [comment]
this turns out to be a duplicate of #505
