### ISSUE TITLE
Let modules register additional steps for first_boot

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#529]
Currently the first_boot module handles a few different tasks:
- Creating initial user and groups
- Setting security access restrictions
- (If configured) Registering and setting up pagekite

My thought is that there should be a list of first boot steps, and any module can add to the list. The step might only be to run a command, or it might include a form to display. Would this make sense?

**Comment by harry-7** [comment]
@jvalleroy  Yes Idea sounds good. I would like to work on this issue. Can you guide me through this?

**Comment by jvalleroy** [comment]
@harry-7 Maybe we can start with the following:
- Move State1 form and view to users module.
- Move State5 form and view to pagekite module.
- first_boot module allows other modules to add URLs to be part of first boot process. I don't exactly know how this would work, but it might be similar to the names module which uses plinth.signals.

**Comment by harry-7** [comment]
@jvalleroy My idea is to use a prefix firstboot in the method names which need to be run at firstboot something like firstboot_<modulename>. During initial setup the first_boot can call them. Is it possible to do this kind of thing ?

**Comment by SunilMohanAdapa** [comment]
@harry-7 , what you are suggesting is quite possible.  Python can enumerate and introspect methods of a module. However, here are some considerations:
* In this scheme, there is no way for modules to specify the order in which the module's first boot component should run with respect to other modules' first boot components.  For example, GPG module's key setup first boot view, will require login to happen from the user's module.  So, the SSH key module's first boot step needs to run after user creation step.
* The method which you talk about must be a view (so that module can decide how the first boot step appears, form is displayed, validated etc.).  Views can be methods or classes.  Of course, we can make sure that classes with name beginning with Firstboot are also considered.  This is looking a bit hacky.
* It is also a convention for us to have views in views.py. But this not always the case. So, where in the module to look for for these methods is not very clear.
* It is not easy for a new developer to understand how the methods are getting called.  Explicitly specifying as part of the module's API (a variable such as is_essential=True) or as part of a method called inside the 'init()' method will be much more easier to understand.

**Comment by SunilMohanAdapa** [comment]
@harry-7, Here is an expansion to @jvalleroy 's proposal.

* Each module that is interested in showing a first boot step will
  declare a variable as follows: `first_boot_steps = [{'id':
  'modstep1', 'url': 'module:step1', 'order': 100}, {'id': 'modstep2',
  'url': 'module:step2', 'order': 200}]`.

* The first boot module will have it's own steps registered in a
  similar manner.

* When a module's first boot step is complete, the module will have to
  call `first_boot.mark_step_done(id)` where id is the same as the id
  in declaration.  There is a possibility to skip steps here.  If step
  y needs to be skipped after step x, then one can call
  `mark_step_done(x)` and `mark_step_done(y)`.

* When the last step marks itself as done, the method will mark entire
  first boot process as done.  This is done with a special key 'first
  boot done' stored in the database.

* The first boot middleware will continue to work the way it is
  currently working, except with one small change.  Instead using the
  current state number to determine if there are any first boot steps
  to run, it will use the special 'first boot done' key as described
  above.

* The first boot module will have a `next_step()` method that will
  determine if there are any steps to run and if so, what the next
  module to run is.  On first call, it enumerates all modules using
  the module loader and creates an ordered list of first boot steps.
  The order specified during the declaration will help here.  When
  `next_step()` is called, it enumerates each step and checks in the
  database if that step is already complete.  The earliest step that
  is not completed will be returned.  The return value is a named URL
  which the caller reverses and redirects to.

@harry-7 , @jvalleroy , please feel free to suggest improvements or alternatives.

**Comment by jvalleroy** [comment]
Fixed in #634.
