### ISSUE TITLE
More strick checks when setting timezone

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/Plinth#554]
Currently, if someone gains access to plinth daemon, they can send a bad value when setting timezone.  This value can contain '..' in the path leading to unexpected results.  Make sure that these cases are properly checked for before attempting to set timezone in actions/timezone-change.

**Comment by bluekeys** [comment]
@arghyatiger have you had much success. Would you like some help?

**Comment by arghyatiger** [comment]
Sir i would love some help. Been stuck since a long time

On Oct 8, 2016 5:17 AM, "David Stephen James Birch" <
notifications@github.com> wrote:

@arghyatiger <https://github.com/arghyatiger> have you had much success.
Would you like some help?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/freedombox/Plinth/issues/554#issuecomment-252386032>,
or mute the thread

**Comment by jvalleroy** [comment]
@arghyatiger How far have you gotten?

Do you need help setting up a development environment, or help understanding this issue, or something more specific?

**Comment by arghyatiger** [comment]
sir, To be very honest, since i just started, i would require help from the
scratch. I.e from setting up the development environment.

**Comment by jvalleroy** [comment]
@arghyatiger You will need these tools to get started:
- git, to clone the plinth repository.
- vagrant, so you can test without changes to your system.
- virtualbox, which runs the VM for vagrant.

**Comment by arghyatiger** [comment]
alright i will start work on it right away !

**Comment by SunilMohanAdapa** [comment]
Fixing #815 will fix this issue.

**Comment by JoKeyser** [comment]
@SunilMohanAdapa, since #815 is fixed now, this issue should be closed too.

**Comment by SunilMohanAdapa** [comment]
@JoKeyser , thanks for the fix.
