### ISSUE TITLE
Plinth needs to know when installing apps is impossible

### ISSUE THREAD

**Issue by mray** [freedombox/Plinth#625]
I just got that motification via plinth: 

> Error installing application: Error during installation E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable) E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?

And it is right: I _am_ trying to upgrade my FreedomBox right now, so actually it is no wonder that installing a new app does not work. But instead of trying and failing plinth should know from the start and do one of those things:
1. Gray out installation options with the reason
2. Display a permanent notification during the time of an upgrade
3. Immediatly pop up an easy to understand message like "FreedomBox is currently busy updating itself ... please try again in a couple of minutes."

**Comment by JoKeyser** [comment]
I agree that users should know this before attempting another install.
I'm lazy and think that 2. would be the easiest to implement, and somewhat sufficient because if people still click an Install button, they get the definitive low-level error. Graying out buttons in addition may make that nicer? I don't know about UI, @mray do you have a revised opinion?

[Over here on Stack Overflow is an implementation](https://stackoverflow.com/questions/23610628/detecting-avoiding-multiple-apt-get-dpkg-installs#25128250) to check if apt/dpkg is currently running, and it works for me within vagrant, the module `fcntl` was already installed. (Note I've only tested during apt-get upgrade.)

Note this issue overlaps with #377, may even be a duplicate; I'm replying here since there's suggestions how to solve it.

**Comment by mray** [comment]
@JoKeyser a revised option may be to do all things at the same time:

1. permanently notify user during upgrade
2. gray out install-buttons
3. install-button link to popup with more information

Given that I have no idea which one is the easiest to tackle I can only say: the more the better,no matter where you start.

Nice to see some activity around that issue :)

**Comment by JoKeyser** [comment]
Hi again, I've made an implementation of 1. and 2., see in screenshot. I don't know what a information a pop-up (3.) could add..?
This information is shown before any application installation or upgrade. I placed it there to not provide useless information to users who are just making settings etc. In vagrant, it's simple to test by invoking `apt-get upgrade` and then leave the installation prompt waiting.

Have a look at the implementation here, https://github.com/JoKeyser/Plinth/tree/playIssue625, I'm not sure whether that's the best places for the code, was a lot of trial and error where to put it. Any opinions?

![dpkgrunningwarning](https://cloud.githubusercontent.com/assets/8722846/25073929/7d290610-22f1-11e7-8fa6-fc9a53a44ea2.png)

**Comment by mray** [comment]
Awesome! This is a great improvement, just looking at the screen-shots. I can't make a judgment on the code part though.

Ideally you should be able to make use of a notification system that does not yet exist. That is why I think making it even better than what you did isn't necessary for now.

Looking forward to see this getting shipped with the next release.

**Comment by JoKeyser** [comment]
Okay great, glad you like it too :). There exists a messaging system, but it didn't seem appropriate for the job, since it allows messages to be clicked away, and I believe they appear anywhere. Will discuss this and the code in a pull request.

**Comment by SunilMohanAdapa** [comment]
Barring minor changes to the code, this issue will be fixed by #812.
