### ISSUE TITLE
Indicator to show if you have the latest version of Plinth

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#687]
This was mentioned in the last progress call (https://wiki.debian.org/FreedomBox/ProgressCalls/2016-12-18).

After a Plinth release is announced, it's not clear when it will show up in unstable / testing / stable. So users might expect an update to happen, but it's not available for them yet.

In Help -> About, we show the current Plinth version. We can also have an indicator to show if a newer version of Plinth is available, in the configured apt source.

**Comment by fonfon** [comment]
You can get the information about the version that would be installed like this:

    >>> import apt
    >>> cache = apt.Cache()
    >>> plinth = cache['plinth']
    >>> plinth.candidate.is_installed
    True

This information has to be provided by the [Help -> about view](../blob/master/plinth/modules/help/help.py), and can then be displayed in the [Help -> about template](../blob/master/plinth/modules/help/templates/help_about.html).

Bonus (optional):
I do not know how long `apt.Cache()` takes on a raspberry pi, on a cubietruck it's 0.25s - maybe it can be made faster by only querying the information of one package instead of all packages. [Here's the documentation of apt](https://apt.alioth.debian.org/python-apt-doc/contents.html#).

**Comment by SunilMohanAdapa** [comment]
There was some discussion earlier about a notification system.  Such as raising a warning when disk space is running low, some urgent problem needs admin's attention.  If we implement this notification system, we could raise a notification event by running a background task and may not have to worry about the performance.

Showing in Help -> About could be a good start too.

**Comment by Pk13055** [comment]
I am new to open source and would like to work on this issue.

**Comment by jvalleroy** [comment]
@Pk13055 Sure, let us know if you have any questions.

**Comment by Pk13055** [comment]
#702 I've made the required changes. Please review and tell me if this is the right way or there's some other way to do it?

**Comment by jvalleroy** [comment]
Fixed in #702. (Maybe the UI can be improved though -- right now it's just a line of text that gets displayed or not.)

**Comment by mray** [comment]
A missing text info is hard to spot. Can't the indication always be there?

**Comment by jvalleroy** [comment]
@mray Yes, I think we should open a new issue to collect ideas for improvements to this feature.
