### ISSUE TITLE
Add Riot/Synapse (matrix.org support)

### ISSUE THREAD

**Issue by mrbiber** [freedombox/Plinth#700]
It would be great if FreedomBox would include the [matrix.org](https://matrix.org) homeserver app [Synapse](https://github.com/matrix-org/synapse/) and the [Riot](https://riot.im) web client. Matrix.org is a decentralized real-time communications protocol, including voice and video chat, featuring end-to-end encryption and based on a completely Free Software stack. Riot is the most advanced client for Matrix.org.

**Comment by jvalleroy** [comment]
In order to add this, we will first need to get the software packaged in Debian. There are .deb packages available, but not uploaded to Debian yet.

These links might be useful for anyone who wants to work on this:
RFP for synapse: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=830601
synapse packaging: https://github.com/matrix-org/package-synapse-debian
There are also a number of dependencies that are provided in http://matrix.org/packages/debian/.

**Comment by mrbiber** [comment]
Synapse is now in Debian unstable: https://tracker.debian.org/pkg/matrix-synapse

**Comment by SunilMohanAdapa** [comment]
Pull request pending #750.  We are close to merging that after sorting out changes needed for federation.

**Comment by SunilMohanAdapa** [comment]
Matrix/Synapse support has been merged into FreedomBox for a while.  I believe we can close this. Any further tweaking can be done as separate issues.

**Comment by mray** [comment]
Please reopen or create a new issue for **RIOT**. We currently only ship a server, GNU/Linux users can easily have a hard time getting the client. No straight forward support in major distros, easy binaries for MacOS and Windows though. Riot homepage currently says:
![image](https://user-images.githubusercontent.com/164785/29241021-7ab9e46c-7f71-11e7-94cb-fdbac27d5773.png)

Inviting people to run their own server just to let them use the ***client*** in the cloud has an ironic taste.
