### ISSUE TITLE
shaarli: Frontpage icon missing

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/Plinth#721]
When Shaarli app is enabled, the frontpage contains a shortcut to launch Shaarli. Icon for this shortcut is missing. This is due missing icon: static/themes/default/shaarli.png.  Fetch, edit dimensions, and add this icon along with proper license entry in LICENSE file.

**Comment by MarkoMackic** [comment]
I think that's not only icon missing, infinoted shorcut icon is missing too, and referecing #720 is this `Gobby Server (infinoted)` label, because paragraph elements are displayed block by default I think, so they have line brake at the end.
![Picture](https://cloud.githubusercontent.com/assets/7548838/22169440/5484ad9c-df74-11e6-88d8-48ce4ea8b56c.png)

**Comment by MarkoMackic** [comment]
Second question is what should be dimensions of icon, I  could fix this issue.

**Comment by jvalleroy** [comment]
@MarkoMackic Regarding the other icons such as infinoted not appearing, this is an issue that I see in vagrant but not in the released images. It's due to "setup.py install" which doesn't reinstall folders that already exist. A workaround for vagrant is to delete /usr/share/plinth/static and then re-run "vagrant provision".

**Comment by jvalleroy** [comment]
Fixed in #725.
