### ISSUE TITLE
Plinth redirecting to same page

### ISSUE THREAD

**Issue by pranithkumar** [freedombox/Plinth#741]
The plinth interface was working fine until I obtained the let's encrypt certificate.After I obtained the let's encrypt certificate the plinth page is not loading. It says that the page is redirecting to itself.
Any help?

**Comment by SunilMohanAdapa** [comment]
@pranithkumar , I got access into the server and fixed the issue.  Here is an analysis:

It turns out that both mod_ssl and mod_gnutls were enabled on this machine.  This is due to machine being upgraded from a much older FreedomBox version.   The version we switched to gnutls is 0.6. At that point were not supporting upgrades from one version to another version.  If we had done this in a more recent version, we should have written to code to disable mod_ssl.  I don't believe we will be fixing this.
