### ISSUE TITLE
add dynamic DNS update support

### ISSUE THREAD

**Issue by steglicd** [freedombox/Plinth#79]
Would be nice if freedombox could be reached via DNS resolved hostname (even if freedombox is connected via dynamic IP).

For this reason I'm implementing a ez-ipupdate module here:
https://github.com/steglicd/Plinth

The module should detect the current WAN IP (even if freedombox is connected behind NAT router) and push the IP to a open source GnudIP server if a change is detected.

IPv6 and other Server types than gnudip should also be included later.

GnudIP vs update URL:
* Gnudip is more safe (md5 hashed and salted password transmission prevent replay attacks)
* update URL is more generic (the most common dynamic DNS Service provides a URL to update the IP)

**Comment by SunilMohanAdapa** [comment]
Cool!  It will take me a few days to clear my backlog and review your changes.  Hopefully, others can do it before that.

Things I noticed at a quick glance:
- You can create a GitHub pull request for the work you did.  This is the usual way to submit changes and allows discussion.  You can do this by creating a branch of your work (git checkout -b dynamicdns), push it and create a pull request from GitHub user interface.
- `dynamicDNS` is rather named `dynamicdns`. We prefer that for python modules and shell scripts.
- Although not strictly necessary, you could use Django FormView to eliminate some boilerplate.
- Pep8 and pylint tools need to run on the code (perhaps you already did this).
- You could use package framework which is about to committed soon instead of message showing that a package is not installed.

**Comment by fonfon** [comment]
This feature is integrated/merged with #81.
