### ISSUE TITLE
Disable "Run Diagsnostics" button from non-running apps

### ISSUE THREAD

**Issue by mray** [freedombox/Plinth#829]
Wouldn't it make sense to remove or disable the `Run Diagnostics` option from apps that are not running?
My understanding is that – by definition – there is no benefit to have them or use them.

**Comment by JoKeyser** [comment]
First I hesitated, but I fully agree now and made a PR.
I initially though it might be useful to check whether the module and firewall is really disabled - but that's a weak argument because it's not clear how to interpret the test outcome (is "failed" good or bad for a non-running app?).
Second, I thought it may be handy to check which ports are used by the app, even if it's not running. But that's also messed up because that's not how it should be. Instead, the ports should be listed alongside other meta-data of the App, somewhere (see  #832).

**Comment by JoKeyser** [comment]
Note, this was solved in PR #865, so this ticket can be closed.
