### ISSUE TITLE
Rename "Configuration" to "System"

### ISSUE THREAD

**Issue by mray** [freedombox/Plinth#892]
@JosephKiranBabu [rightly points out](https://git.snowdrift.coop/sd/design/issues/14) that "System" fits much better as a name for what is currently called "Configuration". There are many things that could need configuration, but there is only one running system.

**Comment by akhil117** [comment]
Can I work on this?

**Comment by akhil117** [comment]
They are many files with word "Configuration" so which files we need to change??

**Comment by JosephKiranBabu** [comment]
@akhil117 As far as this issue is concerned, we have to only change the word "Configuration" in the Plinth UI to "System". 
See [this image](https://wiki.debian.org/FreedomBox/Introduction?action=AttachFile&do=get&target=plinth_all_apps_full_page.png) on the Debian wiki for the location of the word in the UI.

**Comment by JoKeyser** [comment]
Done in PR #1186.
