### ISSUE TITLE
sso: Remote login blocked by our apache config

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#961]
Our apache config for plinth restricts access to local IPs:
https://github.com/freedombox/Plinth/blob/master/data/etc/apache2/sites-available/plinth.conf

This not only prevents you from accessing Plinth remotely, it also blocks applications that use sso like syncthing.

I think we at least need a way to turn off the IP restriction.

**Comment by SunilMohanAdapa** [comment]
Current plan is to open up Pliinth access after doing the following:
- Introduce captcha and show captcha on a few login failures to prevent brute force.  This can be done with django-axes and django-simple-captcha modules.
- Force minimum password length.

@JosephKiranBabu is working these.  But we need to package django-axes for this.

**Comment by JosephKiranBabu** [comment]
**Progress tracker:**

- [x] Remove Apache configuration restricting to local ips
- [x] Add captcha to login screen
- [x] Validate captcha
- [x] Show captcha only if login fails
- [ ] (optional) Captcha refresh
- [x] Audio output with flite
- [x] Increase to 6 characters
- [ ] Use django-axes to determine when to show captcha
- [ ] Use fail2ban to ban the ip after multiple captcha attempts fail
- [ ] Return 403 instead of 200 if login fails
- [ ] Add validation for strong password

**Comment by SunilMohanAdapa** [comment]
If captcha works, we need not consider fail2ban a strong requirement, at least for this release. Also the 403 reporting related to it.

**Comment by JosephKiranBabu** [comment]
@jvalleroy All the required work for this issue is done. #1008 
django-axes packaging is also done. [#874451](https://bugs.debian.org/874451)

**Comment by JosephKiranBabu** [comment]
#1008 is merged. Closing this.
